"""Add objetos_perdidos table

Revision ID: 104ef3072fac
Revises: 
Create Date: 2024-10-07 15:07:03.626300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '104ef3072fac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objetos_perdidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sala_encontrada', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('hora_encontrada', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('fecha_encontrada', sa.Date(), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('descripcion',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('foto',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.LargeBinary(),
               existing_nullable=True)
        batch_op.drop_column('sala')
        batch_op.drop_column('hora')
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objetos_perdidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('hora', mysql.TIME(), nullable=False))
        batch_op.add_column(sa.Column('sala', mysql.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('foto',
               existing_type=sa.LargeBinary(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('descripcion',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('fecha_encontrada')
        batch_op.drop_column('hora_encontrada')
        batch_op.drop_column('sala_encontrada')

    # ### end Alembic commands ###
