"""corrección de relaciones

Revision ID: 29d1f83db4d3
Revises: 3c2b344ec360
Create Date: 2025-05-08 18:08:28.255160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29d1f83db4d3'
down_revision = '3c2b344ec360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CATEGORIA')
    op.drop_table('MARCA')
    op.drop_table('PEDIDO')
    op.drop_table('ETAPA_PEDIDO')
    op.drop_table('PRODUCTO')
    op.drop_table('INVENTARIO')
    op.drop_table('SUCURSAL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SUCURSAL',
    sa.Column('sucursalId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('direccion', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('region', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('comuna', mysql.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('sucursalId'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('INVENTARIO',
    sa.Column('sucursal_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('producto_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stock', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['PRODUCTO.idProducto'], name='INVENTARIO_ibfk_2'),
    sa.ForeignKeyConstraint(['sucursal_id'], ['SUCURSAL.sucursalId'], name='INVENTARIO_ibfk_1'),
    sa.PrimaryKeyConstraint('sucursal_id', 'producto_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('PRODUCTO',
    sa.Column('idProducto', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombreProducto', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('precio', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('marcaId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('categoriaId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('imagen', mysql.LONGBLOB(), nullable=True),
    sa.ForeignKeyConstraint(['categoriaId'], ['CATEGORIA.categoriaId'], name='PRODUCTO_ibfk_2'),
    sa.ForeignKeyConstraint(['marcaId'], ['MARCA.marcaId'], name='PRODUCTO_ibfk_1'),
    sa.PrimaryKeyConstraint('idProducto'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('ETAPA_PEDIDO',
    sa.Column('idEtapaPedido', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('idEtapaPedido'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('PEDIDO',
    sa.Column('idPedido', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clienteId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fechaPedido', sa.DATE(), nullable=True),
    sa.Column('total', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('direccionEnvio', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('sucursalID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('etapaId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clienteId'], ['Usuario.idUsuario'], name='PEDIDO_ibfk_1'),
    sa.ForeignKeyConstraint(['etapaId'], ['ETAPA_PEDIDO.idEtapaPedido'], name='PEDIDO_ibfk_3'),
    sa.ForeignKeyConstraint(['sucursalID'], ['SUCURSAL.sucursalId'], name='PEDIDO_ibfk_2'),
    sa.PrimaryKeyConstraint('idPedido'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('MARCA',
    sa.Column('marcaId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombreMarca', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('marcaId'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('CATEGORIA',
    sa.Column('categoriaId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('categoriaId'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
