"""init schema

Revision ID: 3c2b344ec360
Revises: 
Create Date: 2025-05-08 17:53:54.695247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c2b344ec360'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TIPO_USUARIO',
    sa.Column('idTipoUsuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idTipoUsuario')
    )
    op.create_table('Usuario',
    sa.Column('idUsuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=True),
    sa.Column('apellido', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.Column('telefono', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('tipoUsuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipoUsuario'], ['TIPO_USUARIO.idTipoUsuario'], ),
    sa.PrimaryKeyConstraint('idUsuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Usuario')
    op.drop_table('TIPO_USUARIO')
    # ### end Alembic commands ###
