"""empty message

Revision ID: 6cfe9f3e6884
Revises: 
Create Date: 2025-05-08 22:31:49.404164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6cfe9f3e6884'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PEDIDO', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('direccionEnvio',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=100),
               nullable=False)

    with op.batch_alter_table('PRODUCTO', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
        batch_op.alter_column('apellido',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
        batch_op.alter_column('apellido',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)

    with op.batch_alter_table('PRODUCTO', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=sa.LargeBinary(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    with op.batch_alter_table('PEDIDO', schema=None) as batch_op:
        batch_op.alter_column('direccionEnvio',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=45),
               nullable=True)
        batch_op.alter_column('total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
