"""empty message

Revision ID: b6f36c71b191
Revises: e77d9f4d5d90
Create Date: 2025-05-15 16:02:36.578224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6f36c71b191'
down_revision = 'e77d9f4d5d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('COMENTARIO', schema=None) as batch_op:
        batch_op.drop_constraint('COMENTARIO_ibfk_2_idx', type_='foreignkey')
        batch_op.drop_index('COMENTARIO_ibfk_2_idx_idx')

    op.drop_table('COMENTARIO')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('COMENTARIO',
    sa.Column('idComentario', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('productoId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuarioId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comentario', mysql.LONGTEXT(), nullable=False),
    sa.Column('calificacion', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['productoId'], ['PRODUCTO.idProducto'], name='COMENTARIO_ibfk_2_idx'),
    sa.ForeignKeyConstraint(['usuarioId'], ['Usuario.idUsuario'], name='COMENTARIO_ibfk_1_idx_idx'),
    sa.PrimaryKeyConstraint('idComentario'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('COMENTARIO', schema=None) as batch_op:
        batch_op.create_index('COMENTARIO_ibfk_2_idx_idx', ['productoId'], unique=False)

    # ### end Alembic commands ###
