"""empty message

Revision ID: bf78af7255a9
Revises: 6cfe9f3e6884
Create Date: 2025-05-14 17:09:48.591975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf78af7255a9'
down_revision = '6cfe9f3e6884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MARCA', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MARCA', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
