"""empty message

Revision ID: e77d9f4d5d90
Revises: bf78af7255a9
Create Date: 2025-05-14 17:15:54.986536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77d9f4d5d90'
down_revision = 'bf78af7255a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CARRITO',
    sa.Column('usuarioId', sa.Integer(), nullable=False),
    sa.Column('productoId', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['productoId'], ['PRODUCTO.idProducto'], ),
    sa.ForeignKeyConstraint(['usuarioId'], ['Usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('usuarioId', 'productoId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CARRITO')
    # ### end Alembic commands ###
